name: Build Chrome Extension

on:
  push:
    branches:
      - 'main'
    # tags:
    #   - v*.*.*
jobs:
  build-chrome-extension:
    name: Build Chrome extension artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run build 
        run: yarn build
      - name: Create Package
        run: pushd dist; zip -r ../chrome-extension.zip .; popd
      - name: Archive chrome-extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension
          path: chrome-extension.zip
  # api usage reference:
  # * <https://developer.chrome.com/docs/webstore/using_webstore_api/>
  # * <https://github.com/fregante/chrome-webstore-upload/blob/main/How%20to%20generate%20Google%20API%20keys.md>
  upload-extension:
    name: Upload extension
    runs-on: ubuntu-latest
    needs: build-chrome-extension
    env:
      EXTENSION_ID: fish-tank
      CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - name: Download bundle artifact
        uses: actions/download-artifact@v4
        with:
          name: chrome-extension

      - name: Install webstore cli
        run: |-
          npm install -g chrome-webstore-upload-cli
      - name: Unzip the artifact
        run: |-
          unzip -o chrome-extension.zip -d ./ext-folder
      - name: Upload step
        run: |-
          ls -lhs
          chrome-webstore-upload upload
            --source ext-folder
            --extension-id ${{ env.EXTENSION_ID }}
            --client-id ${{ env.CLIENT_ID }}
            --client-secret ${{ env.CLIENT_SECRET }}
            --refresh-token ${{ env.REFRESH_TOKEN }}
