name: Build Chrome Extension

on:
  push:
    branches:
      - 'main'
    # tags:
    #   - v*.*.*
jobs:
  build-chrome-extension:
    name: Build Chrome extension artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run build 
        run: yarn build
      - name: Create Package
        run: zip -r chrome-extension-${{ github.event.pull_request.head.sha }}.zip dist
      - name: Archive chrome-extension artifact
        uses: actions/upload-artifact@v2
        with:
          name: chrome-extension-${{ github.sha }}
          path: chrome-extension-${{ github.event.pull_request.head.sha }}.zip
  # api usage reference:
  # * <https://developer.chrome.com/docs/webstore/using_webstore_api/>
  # * <https://github.com/fregante/chrome-webstore-upload/blob/main/How%20to%20generate%20Google%20API%20keys.md>
  upload-extension:
    name: Upload extension
    runs-on: ubuntu-latest
    needs: build-chrome-extension
    env:
      EXTENSION_ID: fish-tank

    steps:
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "16.10"

      - name: Download bundle artifact
        uses: actions/download-artifact@v3
        with:
          name: chrome-extension-${{ github.sha }}

      - name: Install webstore cli
        run: |-
          npm install -g chrome-webstore-upload-cli
      
      - name: Upload step
        run: |-
          chrome-webstore-upload upload
            --source chrome-extension-${{ github.sha }}.zip
            --extension-id ${{ env.EXTENSION_ID }}
            --client-id ${{ secrets.GOOGLE_CLIENT_ID }}
            --client-secret ${{ secrets.GOOGLE_CLIENT_SECRET }}
            --refresh-token ${{ secrets.GOOGLE_REFRESH_TOKEN }}
